version: "3.8"

services:
  ciphercorelink:
    build: .
    container_name: ciphercorelink
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    restart: always
