{
  "actions": [
    { "type": "git_clone", "repo": "git@github.com:xxx/yyy.git", "dest": "tmp/yyy" },
    { "type": "run_command", "command": "npm install", "cwd": "tmp/yyy" },
    { "type": "git_commit_push", "repoDir": "tmp/yyy", "message": "autogenerated by AI" },
    { "type": "deploy_docker", "dir": "tmp/yyy/deploy" }
  ]
}