const AIProjectGenerator = require("./AIProjectGenerator");
const AIMonetization = require("./AIMonetization");

class AIAutomation {
  static async run() {
    try {
      // 1. Yangi loyiha yaratish
      const ownerId = "owner_id"; // real owner ID bilan almashtiring
      const project = await AIProjectGenerator.createAutomaticProject({
        ownerId,
        namePrefix: "AI Project",
        descriptionPrefix: "Generated by AI",
      });

      // 2. Metrics yangilash
      const metrics = {
        audienceIncrease: 1000,
        revenueIncrease: 5000,
      };
      await AIProjectGenerator.updateMetrics(project._id, metrics);

      // 3. Monetizatsiya qilish
      await AIMonetization.distributeRevenue(project._id);

      console.log("AI automation completed successfully.");
    } catch (error) {
      console.error("AI automation failed:", error);
    }
  }
}

module.exports = AIAutomation;