const Project = require("../modelda/Project");
const User = require("../modelda/User");

class AIProjectGenerator {
  // projectData: { ownerId, namePrefix, descriptionPrefix }
  static async createAutomaticProject(projectData) {
    const { ownerId, namePrefix, descriptionPrefix } = projectData;

    // Loyihaning nomini va descriptionni avtomatik yaratish
    const timestamp = Date.now();
    const name = `${namePrefix || "AI Project"}-${timestamp}`;
    const description = `${descriptionPrefix || "Generated by AI"} at ${new Date()}`;

    const project = new Project({
      owner: ownerId,
      name,
      description,
      monetizationMode: "aiManaged", // AI tomonidan boshqariladi
      audienceSize: 0,
      totalRevenue: 0,
      customRules: [],
      revenuePool: 0,
    });

    await project.save();
    return project;
  }

  // Auditoriya va daromadni AI avtomatik yangilash
  static async updateMetrics(projectId, metrics) {
    const project = await Project.findById(projectId);
    if (!project) throw new Error("Project not found");

    const { audienceIncrease = 0, revenueIncrease = 0 } = metrics;

    project.audienceSize += audienceIncrease;
    project.totalRevenue += revenueIncrease;
    project.revenuePool += revenueIncrease;

    await project.save();
    return project;
  }
}

module.exports = AIProjectGenerator;